### ISSUE TITLE
无法使用？

### ISSUE THREAD

**Issue by tamakyi** [CCLMSY/nonebot-plugin-sparkapi#1]
python=3.10 on conda
debian11

正常安装并配置好.env之后启动报错如下:
![Screenshot_20240609_010332](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/25850853/91042f11-582f-4f5a-bd98-33ea5e76f9a1)
尝试把报错这部分屏蔽掉之后又有其他地方报错...

**Comment by CCLMSY** [comment]
非常感谢您的反馈！我将在明天进行测试并给您答复。

**Comment by CCLMSY** [comment]
copy了本插件仓库版本（1.4.2）到我的本地测试环境（Python3.11.8 on Conda, Windows 11）并进行测试，没有出现你所描述的问题。
根据你提供的错误信息，初步判断为命令字典sparkapi_commands的字段“help"缺失。
具体原因难以判断，但建议你进行以下排查：
1. 确认"[Bot]\.venv\Lib\site-packages\nonebot_plugin_sparkapi\config.py"中sparkapi_commands对象的"help"字段仍存在/未删除
2. 确认"[Bot]\.env.prod"中不存在"sparkapi_commands"项
如果上述情况均正常，请尝试重新安装本插件。如该问题仍然存在，欢迎继续反馈！

**Comment by tamakyi** [comment]
#确实是.env里面SPARKAPI_COMMANDS__CHAT的问题，屏蔽之后就好了，感谢

**Comment by CCLMSY** [comment]
感谢您的反馈！设置SPARKAPI_COMMANDS__CHAT会覆盖原有的commands字典。这是一个bug，将在今天修复并更新版本。
