### ISSUE TITLE
Bug: 能正常对话但是呼出帮助菜单的时候没反应

### ISSUE THREAD

**Issue by TaSayonara** [CCLMSY/nonebot-plugin-sparkapi#10]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

Win10

### Python 版本

3.11

### 问题描述

正常配置了，机器人是真寻，能正常对话但是呼出帮助菜单的时候没反应
![90038AA4E1A230EE2A3462241528D75F](https://github.com/user-attachments/assets/fc322474-582f-4b6c-a3cb-eda45ae4464a)

### 问题复现

SPARKAPI_MODEL_VERSION='v3.5'            #星火大模型的版本，默认为当前最新。可选值："default", "v4.0", "v3.5", "v3.0", "v2.0", "v1.5"
SPARKAPI_MODEL_TOP_K = 4     #平衡生成文本的质量和多样性。较小的 k 值会减少随机性，使得输出更加稳定；而较大的 k 值会增加随机性，产生更多新颖的输出。取值范围[1, 6]
SPARKAPI_MODEL_TEMPERATURE =   0.5    #控制结果随机性，取值越高随机性越强，即相同的问题得到的不同答案的可能性越高。取值范围 (0，1]
SPARKAPI_MODEL_MAXLENGTH = 8000    #单次上下文最大token长度，v2.0以上建议取值范围：[4000,8000]。详细说明见下文
SPARKAPI_PRIORITY = 80    #本插件响应事件的优先级，建议设置较大的值。可选值：1~97。详细说明见下文
SPARKAPI_COMMAND_CHAT = "/"   # 机器人对话指令，默认为""可直接对话
SPARKAPI_FL_NOTICE = True    #收到对话请求时是否提示“已收到请求”
SPARKAPI_FL_PRIVATE_CHAT = True    #是否允许私聊使用
SPARKAPI_FL_GROUP_PUBLIC = False    #群聊启用公共会话  #True：所有人共享同一会话False：每个人的会话各自独立
SPARKAPI_FL_INTERFLOW = FALSE    #对于同一用户，群聊与私聊数据互通（公共会话启用时，群聊仍独立）
SPARKAPI_FL_GROUP_AT = True    #群聊回复消息时是否需要@提问者
SPARKAPI_FL_IMGGEN =  True    #是否启用AI绘图功能
SPARKAPI_FL_PPTGEN = False    #是否启用AI生成PPT功能
SPARKAPI_IG_SIZE = [648,480]   # AI绘图的图片尺寸，[宽,高]。
SPARKAPI_BOT_NAME = "真寻"    #机器人的名字
COMMAND_START = "/"
![QQ_1722143958604](https://github.com/user-attachments/assets/f704dc8d-d93b-4945-8970-c50062362cf1)

**Comment by CCLMSY** [comment]
已收到你的情况，正在排查

**Comment by CCLMSY** [comment]
请调整SPARKAPI_COMMAND_CHAT = "" # 机器人对话指令，默认为""可直接对话

尝试是否解决这个问题

**Comment by TaSayonara** [comment]
> 请调整SPARKAPI_COMMAND_CHAT = "" # 机器人对话指令，默认为""可直接对话
> 
> 尝试是否解决这个问题

之前就是没加"/"，也是同样的问题

**Comment by CCLMSY** [comment]
请添加我的QQ：2502408581进一步联系

**Comment by CCLMSY** [comment]
已协助你解决问题//感谢你的使用！

**Comment by akua0z** [comment]
> > 请调整SPARKAPI_COMMAND_CHAT = "" # 机器人对话指令，默认为""可直接对话
> > 
> > 尝试是否解决这个问题
> 
> 之前就是没加"/"，也是同样的问题

遇到了和你一样的问题，请问你最终如何解决的？
