### ISSUE TITLE
Bug: 似乎无法使用联网查询的功能

### ISSUE THREAD

**Issue by hustharry** [CCLMSY/nonebot-plugin-sparkapi#14]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

Windows 11

### Python 版本

3.11.8

### 问题描述

在onebotV11的QQ平台上接入此插件，通过关键词**“搜索”**来触发联网搜索，只返回一句**“正在搜索中”**，按照讯飞官方文档的说法，需要用户自行拼接多次返回的值

### 问题复现

按照文档正常配置

### 期望行为

能够多次发送联网结果

**Comment by CCLMSY** [comment]
请提供一些对话截图以便我们测试与排查问题^_^

**Comment by hustharry** [comment]
对话截图如下，
![IMG_20240929_113429](https://github.com/user-attachments/assets/3f8c114c-8072-46b4-91aa-cc6c413f74a6)

**Comment by CCLMSY** [comment]
在2.x版本开发之初，还没有提供tool相关选项，因此暂不支持联网功能。
我们会重视这个配置项，在未来的更新中引入这项需求的实现。

作者大三，近期学业较为繁忙，业余时间来写，更新可能会比较长。
也推荐你自行阅读源码，在本地新增tool的配置项以支持联网搜索。

**Comment by hustharry** [comment]
好的，感谢作者解答，我本地先试着改改
