### ISSUE TITLE
Bug: 配置app相关信息后无法使用大部分功能

### ISSUE THREAD

**Issue by qixiabanyi** [CCLMSY/nonebot-plugin-sparkapi#15]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

Windows 11

### Python 版本

3.12.7

### 问题描述

preset无法创建
无法开启对话

### 问题复现

我配置了SPARKAPI_APP_ID, SPARKAPI_API_SECRET, SPARKAPI_API_KEY
在私聊界面中输入“你好呀”后台可以收到消息但无回应
输入help有指令查看界面弹出
create角色无法成功

### 截图或日志

![Uploading 屏幕截图 2024-10-28 003102.png…]()

**Comment by CCLMSY** [comment]
已经收到你的issue，但是你的截图没有上传成功。
我现在进行当前版本测试，稍后回复你

**Comment by qixiabanyi** [comment]
> 已经收到你的issue，但是你的截图没有上传成功。 我现在进行当前版本测试，稍后回复你

![屏幕截图 2024-10-28 003102](https://github.com/user-attachments/assets/6aeb0ced-99ac-45ac-b021-aef4a69eac51)

**Comment by CCLMSY** [comment]
你好，确认你所述的无法创建预设的情况是一个Bug。
我已经修复了这个问题并发布了新的版本（v2.0.9），你稍后可以尝试更新使用一下。

此外，本地没有遇到你所述的无法开启对话的问题。
你可以使用新版本重新尝试会话功能，如果仍有问题欢迎反馈，并附带相关错误信息//
