### ISSUE TITLE
请问内容重复是什么原因

### ISSUE THREAD

**Issue by akua0z** [CCLMSY/nonebot-plugin-sparkapi#17]
![Screenshot_2024-11-28-10-41-56-456_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/a4ef543a-d3e4-4673-8195-d9b724341651)

是插件配置的问题吗

**Comment by CCLMSY** [comment]
很抱歉没有及时回复你的issue，如果问题仍然存在，请联系2502408581（QV同号）获取帮助
