### ISSUE TITLE
Feature: 支持zhenxun-bot

### ISSUE THREAD

**Issue by ThelevenFD** [CCLMSY/nonebot-plugin-sparkapi#18]
### Self-check

- [X] 我已明确我的需求
- [X] 这个需求与本项目具有相关性

### 需求描述

zhenxun-bot 依赖 nonebot-plugin-session 版本 ^0.2.3
nonebot-plugin-sparkapi（版本 ^2.0.9）依赖 nonebot-plugin-session 版本 >=0.3.2。

### 期望效果

是否能降级兼容一下（（

**Comment by Onimaimai** [comment]
你把真寻目录里的pyproject.toml改为nonebot-plugin-session=^0.3再poetry update就好了
