### ISSUE TITLE
发送信息报错：连接服务器失败！ 错误信息：[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by 237715463** [CCLMSY/nonebot-plugin-sparkapi#2]
![Clip_2024-06-26_14-10-05](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/128313546/e4cfc132-67f4-4b16-9377-f5c1b67ef719)
![Clip_2024-06-26_14-14-23](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/128313546/51ff7dd7-d5e4-443b-8050-94a20856e7fa)

**Comment by CCLMSY** [comment]
收到，预计在今晚进行测试并给出答复

**Comment by CCLMSY** [comment]
请问你在出现这个问题时，有开启扩展功能（图片生成/PPT生成）吗？

**Comment by 237715463** [comment]
星火那边开通了一大堆功能，但是nonebot2配置选项没有开启扩展功能（图片生成/PPT生成）

**Comment by CCLMSY** [comment]
实际上我指的是本插件的配置项。
这些配置项默认是关闭的，那应该是没有开启扩展功能的。

对话功能的请求是用讯飞官方的demo，我一会儿去看一下文档有没有变更。
预计今晚给出答复。

**Comment by CCLMSY** [comment]
copy了本插件仓库版本（1.4.4）到我的本地测试环境（Python3.11.8 on Conda, Windows 11）并进行测试，没有出现你所描述的问题。
根据你提供的错误信息，对本插件进行了调整，并发布了新的1.4.5版本。请尝试更新本插件，如该问题仍然存在，欢迎继续反馈！

**Comment by 237715463** [comment]
应该是系统问题，我用服务器win2012就不行，换回工作电脑win10就没有问题

**Comment by 237715463** [comment]
尝试了，还是不得，所有才在win10系统尝试
