### ISSUE TITLE
包 nonebot-plugin-sparkapi 未找到

### ISSUE THREAD

**Issue by 1296lol** [CCLMSY/nonebot-plugin-sparkapi#3]
如图所示
![QQ截图20240626153657](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/137581352/19a8a869-cd6f-41d8-a551-29c9d0b48d98)

**Comment by 1296lol** [comment]
试了其他插件，就这个不行

**Comment by CCLMSY** [comment]
已经收到你的情况，正在排查，稍后回复

**Comment by CCLMSY** [comment]
检查了Nonebot商店和PyPI的上架情况，没有发现异常。
在我的本地测试环境（Python3.11.8 on Conda, Windows 11）进行了如下测试（命令由README.md中复制），插件安装并没有出现你所述的问题：
![image](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/145911132/fcdfca3d-7e89-4dc2-81fe-c55c10a3bfc1)

根据你提供的错误信息，排除了未正确安装Nonebot2的可能性，初步判断具体原因可能与你本地的pip有关（如果创建了虚拟环境，则为虚拟环境的pip，检查问题前请激活虚拟环境）。
具体原因难以确定，建议你做以下排查：
1. pip版本是否为最新，有时候pip 的版本较旧会导致找不到新发布的包。尝试使用以下命令更新pip：
```
pip install --upgrade pip
```
2. pip源是否更改到了第三方源（一些第三方源的更新可能有滞后性）

如果上述情况均正常，欢迎继续反馈！需要协助也可以联系我。

**Comment by 1296lol** [comment]
经过你的反馈，检查仍然无其他问题

![image](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/137581352/49816389-b73a-4cc3-a952-d14ee7d86c8f)

pip版本已经是最新，且使用默认源。

![image](https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/137581352/324f937e-2a81-40e2-a587-89b2a5a7e2f4)

测试其他插件但是能正常下载安装

**Comment by CCLMSY** [comment]
请添加我的QQ：2502408581，以便进一步交流

**Comment by CCLMSY** [comment]
已为你解决问题，感谢你的使用！
