### ISSUE TITLE
填了.env配置项后插件无法加载

### ISSUE THREAD

**Issue by a114511a** [CCLMSY/nonebot-plugin-sparkapi#4]
ntqq + nonebot2
<img width="781" alt="image" src="https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/152017388/05064ae8-4b90-4a0e-9324-522f15ac2383">
<img width="555" alt="image" src="https://github.com/CCLMSY/nonebot-plugin-sparkapi/assets/152017388/a5f39d3c-75ff-42e2-ace9-508fb6a9ce6a">

**Comment by CCLMSY** [comment]
btw，本项目已经重构完成，撰写完文档后推出，和目前的差别较大
//你可以明天再关注一下本项目更新，感谢你的使用！
喜欢本项目的话请点个Star⭐谢谢喵~

**Comment by a114511a** [comment]
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
谢谢，但连上后出现这个报错信息，是网络环境原因导致的吗

**Comment by CCLMSY** [comment]
你使用的操作系统和python环境是？

**Comment by a114511a** [comment]
windows sever 2019 python3.12.4

**Comment by CCLMSY** [comment]
参考这个issue：https://github.com/CCLMSY/nonebot-plugin-sparkapi/issues/2
项目开发时使用的是（Python3.11.8 on Conda, Windows 11），没有考虑到这个情况
目前没有合适的解决方法，在下个版本推出后会尝试寻找解决方案//

**Comment by CCLMSY** [comment]
你好，你可以尝试在本地安装SSL证书来解决这个问题。
此外，刚才推送的2.0.2版本尝试通过不验证SSL证书来规避这个情况，你可以尝试一下。
