### ISSUE TITLE
Bug: 报错

### ISSUE THREAD

**Issue by Cvandia** [CCLMSY/nonebot-plugin-sparkapi#5]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

windows 10

### Python 版本

3.10.8

### 问题描述

出现json解析错误和字符编码错误

### 问题复现

配置了
![image](https://github.com/user-attachments/assets/4d9037c9-ba37-441b-8b18-7d309987c745)

### 截图或日志

![ef0b6d6d868f0f0099cf6a14ee1e90f2](https://github.com/user-attachments/assets/888d0ef1-7aea-4883-a8f1-ce03adca5a96)

**Comment by CCLMSY** [comment]
你好，我已经收到了你的问题，现在进行测试

**Comment by CCLMSY** [comment]
你好！
在我的本地测试环境（Python3.11.8 on Conda, Windows 11）进行了如下测试：
重新安装BOT和插件。消息存储和收发正常。

根据你提供的错误信息，猜测是由于我为了存储文件的可读性，在设置json存储时关闭了强制ASCII，导致不同版本json读取有差异。

刚才推送了新版本（v2.0.3）重新打开了强制ASCII存储，你可以尝试更新到此版本，大概率能够解决这个问题。
请注意：在更新完插件后，请先删除BOT项目文件夹下的SparkApi文件夹，清除所有缓存。

如果问题仍然存在，欢迎继续反馈！

**Comment by Cvandia** [comment]
好的，已成功解决问题，感谢作者解答与更新，谢谢！
