### ISSUE TITLE
Bug: 对话请求失败

### ISSUE THREAD

**Issue by Wexevou** [CCLMSY/nonebot-plugin-sparkapi#6]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

Win10

### Python 版本

3.10

### 问题描述

![QQ_1720979344311](https://github.com/user-attachments/assets/da516f09-9100-4242-8efb-effc5b97220f)

### 问题复现

![QQ_1720979486853](https://github.com/user-attachments/assets/b48ff784-df38-4f42-a34c-3255c4edb823)

**Comment by CCLMSY** [comment]
你好，v1.5(Lite)版本模型最高只支持4096token长度（由于版本较旧，我在阅读官方文档的时候没有注意到，非常抱歉🥺）

要解决这个问题，你可在.env文件中配置：SPARKAPI_MODEL_MAXLENGTH=4000

这个情况会在下个版本做特殊处理

此外，v1.5版本性能较差，建议你使用耿新的版本//使用范围不大的情况下赠送的用量是足够使用的

**Comment by Wexevou** [comment]
设置了配置貌似还是无用

**Comment by CCLMSY** [comment]
请添加我的QQ：2502408581，我远程看一下你的问题

**Comment by Wexevou** [comment]
> 请添加我的QQ：2502408581，我远程看一下你的问题

已加

**Comment by CCLMSY** [comment]
v2.0.6版本已修复此问题
