### ISSUE TITLE
Bug: 对话请求失败

### ISSUE THREAD

**Issue by enKl03B** [CCLMSY/nonebot-plugin-sparkapi#8]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

Windows 11

### Python 版本

3.10（微软商店版本）

### 问题描述

已经正确填写了文档中的必填项，但收不到回复并报错
模型是spark lite

### 问题复现

如上

### 截图或日志

对话请求失败！请联系开发者。
错误信息：<class 'Exception'>:请求错误: Code:11200, Data:{'header': {'code': 11200, 'message': 'AppIdNoAuthError:(17:27:05.718) tokens.total', 'sid': 'cht000b806d@dx190d9c418f5b808560', 'status': 2}}

**Comment by CCLMSY** [comment]
![image](https://github.com/user-attachments/assets/08dc2cdd-9a3c-4546-bd88-1dfafab837c9)

参考讯飞API文档，有较大概率是你的控制台应用未取得功能授权。请前往讯飞开放平台控制台检查权限。

**Comment by enKl03B** [comment]
已经解决，只要指定模型版本即可，谢谢解答
